site_name: BLUX Ecosystem
site_description: Enterprise documentation hub for the BLUX constellation
site_url: https://outer-void.github.io/blux-ecosystem
repo_url: https://github.com/Outer-Void/blux-ecosystem
repo_name: Outer-Void/blux-ecosystem
nav:
  - Overview: index.md
  - Vision: VISION.md
  - Architecture: ARCHITECTURE.md
  - Install: INSTALL.md
  - Operations: OPERATIONS.md
  - Security: SECURITY.md
  - Privacy: PRIVACY.md
  - Configuration: CONFIGURATION.md
  - Troubleshooting: TROUBLESHOOTING.md
  - Governance: GOVERNANCE.md
  - Contributing: CONTRIBUTING.md
  - Support: SUPPORT.md
  - Roadmap: ROADMAP.md
  - Change Log: CHANGELOG.md
  - Modules:
      - BLUX Lite: modules/blux-lite/README.md
      - BLUX cA: modules/blux-ca/README.md
      - BLUX Guard: modules/blux-guard/README.md
      - BLUX Quantum (CLI): modules/blux-quantum/README.md
      - BLUX Doctrine: modules/blux-doctrine/README.md
      - BLUX Commander: modules/blux-commander/README.md
      - BLUX Reg: modules/blux-reg/README.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Outer-Void/blux-ecosystem
