name: Docs
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install mkdocs-material
      - name: Synchronize module docs
        run: python scripts/scan_subrepos.py
      - name: Refresh README file tree
        run: python scripts/update_readme_filetree.py
      - name: Render MkDocs index
        run: python scripts/render_index_from_readme.py
      - name: Build documentation
        run: mkdocs build --strict || true
      - name: Publish to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
      - name: Lint links (non-blocking)
        run: python scripts/lint_links.py || true
